/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 29 07:10:15 GMT 2021
 */

package org.apache.bcel.generic;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.bcel.generic.ConstantPoolGen;

public class ConstantPoolGen_21_Test {

  //Covered goal: org.apache.bcel.generic.ConstantPoolGen.lookupDouble(D)I: path condition EvoSuiteWrapper_21 (id = 0)

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ConstantPoolGen constantPoolGen0 = new ConstantPoolGen();
      float float0 = 0.0F;
      constantPoolGen0.lookupDouble(float0);
  }
}
