/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 29 07:09:12 GMT 2021
 */

package org.apache.bcel.generic;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.bcel.generic.ConstantPoolGen;

public class ConstantPoolGen_18_Test {

  //Covered goal: org.apache.bcel.generic.ConstantPoolGen.getSize()I: path condition EvoSuiteWrapper_18 (id = 0)

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ConstantPoolGen constantPoolGen0 = new ConstantPoolGen();
      constantPoolGen0.getSize();
  }
}
