/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 16 20:51:46 GMT 2021
 */

package org.apache.bcel.classfile;

import org.junit.Test;
import static org.junit.Assert.*;
import java.io.InputStream;
import org.apache.bcel.classfile.JavaClass;
import org.apache.bcel.classfile.Method;
import org.apache.bcel.util.ClassLoaderRepository;
import org.apache.bcel.util.ClassPath;
import org.apache.bcel.util.ClassPathRepository;
import org.apache.bcel.util.SyntheticRepository;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AccessFlags_ESTest extends AccessFlags_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Method method0 = new Method();
      int int0 = method0.getAccessFlags();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
      ClassLoaderRepository classLoaderRepository0 = new ClassLoaderRepository(classLoader0);
      Class<InputStream> class0 = InputStream.class;
      JavaClass javaClass0 = classLoaderRepository0.loadClass(class0);
      javaClass0.setAccessFlags(1747);
      boolean boolean0 = javaClass0.isInterface();
      assertEquals(1747, javaClass0.getModifiers());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
      ClassLoaderRepository classLoaderRepository0 = new ClassLoaderRepository(classLoader0);
      Class<String> class0 = String.class;
      JavaClass javaClass0 = classLoaderRepository0.loadClass(class0);
      boolean boolean0 = javaClass0.isInterface();
      assertFalse(boolean0);
      assertTrue(javaClass0.isPublic());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ClassPath classPath0 = new ClassPath("j\u0004t5dl15pZ,'xY?3");
      ClassPathRepository classPathRepository0 = new ClassPathRepository(classPath0);
      Class<InputStream> class0 = InputStream.class;
      JavaClass javaClass0 = classPathRepository0.loadClass(class0);
      int int0 = javaClass0.getAccessFlags();
      assertEquals(1057, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
      ClassLoaderRepository classLoaderRepository0 = new ClassLoaderRepository(classLoader0);
      Class<String> class0 = String.class;
      JavaClass javaClass0 = classLoaderRepository0.loadClass(class0);
      javaClass0.isTransient(true);
      boolean boolean0 = javaClass0.isVarArgs();
      assertEquals(177, javaClass0.getModifiers());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Method method0 = new Method();
      boolean boolean0 = method0.isVarArgs();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
      ClassLoaderRepository classLoaderRepository0 = new ClassLoaderRepository(classLoader0);
      Class<InputStream> class0 = InputStream.class;
      JavaClass javaClass0 = classLoaderRepository0.loadClass(class0);
      javaClass0.setAccessFlags((-1937));
      boolean boolean0 = javaClass0.isEnum();
      assertEquals((-1937), javaClass0.getAccessFlags());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
      ClassLoaderRepository classLoaderRepository0 = new ClassLoaderRepository(classLoader0);
      Class<InputStream> class0 = InputStream.class;
      JavaClass javaClass0 = classLoaderRepository0.loadClass(class0);
      boolean boolean0 = javaClass0.isEnum();
      assertFalse(boolean0);
      assertEquals(1057, javaClass0.getModifiers());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
      ClassLoaderRepository classLoaderRepository0 = new ClassLoaderRepository(classLoader0);
      Class<InputStream> class0 = InputStream.class;
      JavaClass javaClass0 = classLoaderRepository0.loadClass(class0);
      javaClass0.setAccessFlags((-1937));
      boolean boolean0 = javaClass0.isAnnotation();
      assertEquals((-1937), javaClass0.getAccessFlags());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ClassPath classPath0 = ClassPath.SYSTEM_CLASS_PATH;
      ClassPathRepository classPathRepository0 = new ClassPathRepository(classPath0);
      Class<String> class0 = String.class;
      JavaClass javaClass0 = classPathRepository0.loadClass(class0);
      boolean boolean0 = javaClass0.isAnnotation();
      assertFalse(boolean0);
      assertTrue(javaClass0.isPublic());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SyntheticRepository syntheticRepository0 = SyntheticRepository.getInstance();
      Class<InputStream> class0 = InputStream.class;
      JavaClass javaClass0 = syntheticRepository0.loadClass(class0);
      boolean boolean0 = javaClass0.isSynthetic();
      //  // Unstable assertion: assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SyntheticRepository syntheticRepository0 = SyntheticRepository.getInstance();
      Class<InputStream> class0 = InputStream.class;
      JavaClass javaClass0 = syntheticRepository0.loadClass(class0);
      boolean boolean0 = javaClass0.isStrictfp();
      //  // Unstable assertion: assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ClassPath classPath0 = ClassPath.SYSTEM_CLASS_PATH;
      ClassPathRepository classPathRepository0 = new ClassPathRepository(classPath0);
      Class<String> class0 = String.class;
      JavaClass javaClass0 = classPathRepository0.loadClass(class0);
      javaClass0.isAbstract(true);
      boolean boolean0 = javaClass0.isAbstract();
      assertEquals(1073, javaClass0.getAccessFlags());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Method method0 = new Method();
      boolean boolean0 = method0.isAbstract();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
      ClassLoaderRepository classLoaderRepository0 = new ClassLoaderRepository(classLoader0);
      Class<String> class0 = String.class;
      JavaClass javaClass0 = classLoaderRepository0.loadClass(class0);
      boolean boolean0 = javaClass0.isNative();
      assertFalse(boolean0);
      assertTrue(javaClass0.isPublic());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      SyntheticRepository syntheticRepository0 = SyntheticRepository.getInstance();
      Class<InputStream> class0 = InputStream.class;
      JavaClass javaClass0 = syntheticRepository0.loadClass(class0);
      JavaClass javaClass1 = javaClass0.getSuperClass();
      boolean boolean0 = javaClass1.isTransient();
      //  // Unstable assertion: assertTrue(javaClass0.isTransient());
      //  // Unstable assertion: assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      SyntheticRepository syntheticRepository0 = SyntheticRepository.getInstance();
      Class<InputStream> class0 = InputStream.class;
      JavaClass javaClass0 = syntheticRepository0.loadClass(class0);
      boolean boolean0 = javaClass0.isTransient();
      //  // Unstable assertion: assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ClassPath classPath0 = new ClassPath("j\u0004t5dl15pZ,'xY?3");
      ClassPathRepository classPathRepository0 = new ClassPathRepository(classPath0);
      Class<InputStream> class0 = InputStream.class;
      JavaClass javaClass0 = classPathRepository0.loadClass(class0);
      boolean boolean0 = javaClass0.isVolatile();
      assertTrue(javaClass0.isPublic());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      SyntheticRepository syntheticRepository0 = SyntheticRepository.getInstance();
      Class<InputStream> class0 = InputStream.class;
      JavaClass javaClass0 = syntheticRepository0.loadClass(class0);
      boolean boolean0 = javaClass0.isSynchronized();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Method method0 = new Method();
      boolean boolean0 = method0.isSynchronized();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      SyntheticRepository syntheticRepository0 = SyntheticRepository.getInstance();
      Class<Integer> class0 = Integer.class;
      JavaClass javaClass0 = syntheticRepository0.loadClass(class0);
      boolean boolean0 = javaClass0.isFinal();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      SyntheticRepository syntheticRepository0 = SyntheticRepository.getInstance();
      Class<InputStream> class0 = InputStream.class;
      JavaClass javaClass0 = syntheticRepository0.loadClass(class0);
      boolean boolean0 = javaClass0.isFinal();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      ClassPath classPath0 = ClassPath.SYSTEM_CLASS_PATH;
      SyntheticRepository syntheticRepository0 = SyntheticRepository.getInstance(classPath0);
      Class<Object> class0 = Object.class;
      JavaClass javaClass0 = syntheticRepository0.loadClass(class0);
      boolean boolean0 = javaClass0.isStatic();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
      ClassLoaderRepository classLoaderRepository0 = new ClassLoaderRepository(classLoader0);
      Class<InputStream> class0 = InputStream.class;
      JavaClass javaClass0 = classLoaderRepository0.loadClass(class0);
      javaClass0.setAccessFlags((-1937));
      boolean boolean0 = javaClass0.isProtected();
      assertEquals((-1937), javaClass0.getModifiers());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
      ClassLoaderRepository classLoaderRepository0 = new ClassLoaderRepository(classLoader0);
      Class<InputStream> class0 = InputStream.class;
      JavaClass javaClass0 = classLoaderRepository0.loadClass(class0);
      boolean boolean0 = javaClass0.isProtected();
      assertFalse(boolean0);
      assertEquals(1057, javaClass0.getAccessFlags());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      ClassPath classPath0 = new ClassPath("j\u0004t5dl15pZ,'xY?3");
      ClassPathRepository classPathRepository0 = new ClassPathRepository(classPath0);
      Class<InputStream> class0 = InputStream.class;
      JavaClass javaClass0 = classPathRepository0.loadClass(class0);
      boolean boolean0 = javaClass0.isPrivate();
      assertFalse(boolean0);
      assertEquals(1057, javaClass0.getModifiers());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      SyntheticRepository syntheticRepository0 = SyntheticRepository.getInstance();
      Class<InputStream> class0 = InputStream.class;
      JavaClass javaClass0 = syntheticRepository0.loadClass(class0);
      boolean boolean0 = javaClass0.isPublic();
      //  // Unstable assertion: assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      SyntheticRepository syntheticRepository0 = SyntheticRepository.getInstance();
      Class<InputStream> class0 = InputStream.class;
      JavaClass javaClass0 = syntheticRepository0.loadClass(class0);
      javaClass0.isAbstract(false);
      //  // Unstable assertion: assertEquals(343, javaClass0.getAccessFlags());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      SyntheticRepository syntheticRepository0 = SyntheticRepository.getInstance();
      Class<InputStream> class0 = InputStream.class;
      JavaClass javaClass0 = syntheticRepository0.loadClass(class0);
      javaClass0.isTransient(false);
      //  // Unstable assertion: assertEquals((-471), javaClass0.getModifiers());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      SyntheticRepository syntheticRepository0 = SyntheticRepository.getInstance();
      Class<InputStream> class0 = InputStream.class;
      JavaClass javaClass0 = syntheticRepository0.loadClass(class0);
      javaClass0.isStatic(false);
      //  // Unstable assertion: assertEquals(464, javaClass0.getModifiers());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      SyntheticRepository syntheticRepository0 = SyntheticRepository.getInstance();
      Class<InputStream> class0 = InputStream.class;
      JavaClass javaClass0 = syntheticRepository0.loadClass(class0);
      //  // Unstable assertion: assertTrue(javaClass0.isInterface());
      
      javaClass0.setModifiers(465);
      //  // Unstable assertion: assertFalse(javaClass0.isAnnotation());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      ClassPath classPath0 = new ClassPath("j\u0004t5dl15pZ,'xY?3");
      ClassPathRepository classPathRepository0 = new ClassPathRepository(classPath0);
      Class<InputStream> class0 = InputStream.class;
      JavaClass javaClass0 = classPathRepository0.loadClass(class0);
      assertTrue(javaClass0.isPublic());
      
      javaClass0.isPublic(false);
      assertEquals(1056, javaClass0.getModifiers());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Method method0 = new Method();
      method0.isSynthetic(true);
      assertEquals(4096, method0.getModifiers());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      ClassPathRepository classPathRepository0 = new ClassPathRepository((ClassPath) null);
      Class<Object> class0 = Object.class;
      JavaClass javaClass0 = classPathRepository0.loadClass(class0);
      javaClass0.isVolatile(false);
      assertEquals(33, javaClass0.getAccessFlags());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      ClassPath classPath0 = ClassPath.SYSTEM_CLASS_PATH;
      ClassPathRepository classPathRepository0 = new ClassPathRepository(classPath0);
      Class<String> class0 = String.class;
      JavaClass javaClass0 = classPathRepository0.loadClass(class0);
      javaClass0.isProtected(true);
      assertEquals(53, javaClass0.getModifiers());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Method method0 = new Method();
      method0.isSynchronized(true);
      assertTrue(method0.isSynchronized());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      SyntheticRepository syntheticRepository0 = SyntheticRepository.getInstance();
      Class<InputStream> class0 = InputStream.class;
      JavaClass javaClass0 = syntheticRepository0.loadClass(class0);
      javaClass0.isAnnotation(true);
      assertTrue(javaClass0.isAnnotation());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      SyntheticRepository syntheticRepository0 = SyntheticRepository.getInstance();
      Class<InputStream> class0 = InputStream.class;
      JavaClass javaClass0 = syntheticRepository0.loadClass(class0);
      javaClass0.isInterface(true);
      //  // Unstable assertion: assertEquals((-3105), javaClass0.getModifiers());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      SyntheticRepository syntheticRepository0 = SyntheticRepository.getInstance();
      Class<InputStream> class0 = InputStream.class;
      JavaClass javaClass0 = syntheticRepository0.loadClass(class0);
      javaClass0.isPrivate(true);
      assertTrue(javaClass0.isPrivate());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      ClassPath classPath0 = new ClassPath("j\u0004t5dl15pZ,'xY?3");
      ClassPathRepository classPathRepository0 = new ClassPathRepository(classPath0);
      Class<InputStream> class0 = InputStream.class;
      JavaClass javaClass0 = classPathRepository0.loadClass(class0);
      javaClass0.isVarArgs(false);
      assertEquals(1057, javaClass0.getModifiers());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      SyntheticRepository syntheticRepository0 = SyntheticRepository.getInstance();
      Class<InputStream> class0 = InputStream.class;
      JavaClass javaClass0 = syntheticRepository0.loadClass(class0);
      javaClass0.isStrictfp(false);
      assertEquals(1057, javaClass0.getAccessFlags());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      ClassPath classPath0 = ClassPath.SYSTEM_CLASS_PATH;
      ClassPathRepository classPathRepository0 = new ClassPathRepository(classPath0);
      Class<String> class0 = String.class;
      JavaClass javaClass0 = classPathRepository0.loadClass(class0);
      int int0 = javaClass0.getModifiers();
      assertEquals(49, int0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      ClassPath classPath0 = ClassPath.SYSTEM_CLASS_PATH;
      ClassPathRepository classPathRepository0 = new ClassPathRepository(classPath0);
      Class<String> class0 = String.class;
      JavaClass javaClass0 = classPathRepository0.loadClass(class0);
      javaClass0.isFinal(true);
      assertEquals(49, javaClass0.getModifiers());
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
      ClassLoaderRepository classLoaderRepository0 = new ClassLoaderRepository(classLoader0);
      Class<InputStream> class0 = InputStream.class;
      JavaClass javaClass0 = classLoaderRepository0.loadClass(class0);
      javaClass0.isEnum(false);
      assertEquals(1057, javaClass0.getAccessFlags());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      ClassPath classPath0 = new ClassPath("j\u0004t5dl15pZ,'xY?3");
      ClassPathRepository classPathRepository0 = new ClassPathRepository(classPath0);
      Class<InputStream> class0 = InputStream.class;
      JavaClass javaClass0 = classPathRepository0.loadClass(class0);
      javaClass0.isNative(true);
      assertEquals(1313, javaClass0.getAccessFlags());
  }
}
