/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 16 20:07:49 GMT 2021
 */

package org.apache.bcel.classfile;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.DataInput;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.EOFException;
import java.io.FileDescriptor;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PipedInputStream;
import java.io.PipedOutputStream;
import org.apache.bcel.classfile.Attribute;
import org.apache.bcel.classfile.Constant;
import org.apache.bcel.classfile.ConstantPool;
import org.apache.bcel.classfile.EmptyVisitor;
import org.apache.bcel.classfile.Synthetic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockFileInputStream;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Synthetic_ESTest extends Synthetic_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      byte[] byteArray0 = new byte[8];
      Constant[] constantArray0 = new Constant[0];
      ConstantPool constantPool0 = new ConstantPool(constantArray0);
      Synthetic synthetic0 = new Synthetic(45, 147, byteArray0, constantPool0);
      ConstantPool constantPool1 = constantPool0.copy();
      Attribute attribute0 = synthetic0.copy(constantPool1);
      assertNotSame(attribute0, synthetic0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      ConstantPool constantPool0 = new ConstantPool((Constant[]) null);
      Synthetic synthetic0 = new Synthetic((-2520), (-1483), byteArray0, constantPool0);
      String string0 = synthetic0.toString();
      assertEquals("Synthetic", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Synthetic synthetic0 = new Synthetic(24, (-1), (DataInput) null, (ConstantPool) null);
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream(pipedInputStream0);
      DataOutputStream dataOutputStream0 = new DataOutputStream(pipedOutputStream0);
      synthetic0.dump(dataOutputStream0);
      assertEquals((-1), synthetic0.getLength());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Synthetic synthetic0 = null;
      try {
        synthetic0 = new Synthetic(379, 239, (DataInput) null, (ConstantPool) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bcel.classfile.Synthetic", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      DataInputStream dataInputStream0 = new DataInputStream((InputStream) null);
      Synthetic synthetic0 = new Synthetic(0, 0, dataInputStream0, (ConstantPool) null);
      byte[] byteArray0 = new byte[4];
      synthetic0.setBytes(byteArray0);
      byte[] byteArray1 = synthetic0.getBytes();
      assertEquals(4, byteArray1.length);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      Constant[] constantArray0 = new Constant[0];
      ConstantPool constantPool0 = new ConstantPool(constantArray0);
      Synthetic synthetic0 = new Synthetic((-3229), (-3229), byteArray0, constantPool0);
      byte[] byteArray1 = synthetic0.getBytes();
      assertArrayEquals(new byte[] {}, byteArray1);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      ConstantPool constantPool0 = new ConstantPool((Constant[]) null);
      Synthetic synthetic0 = new Synthetic((-2520), (-1483), byteArray0, constantPool0);
      Attribute attribute0 = synthetic0.copy(constantPool0);
      assertNotSame(attribute0, synthetic0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Synthetic synthetic0 = new Synthetic(1912, 1912, (byte[]) null, (ConstantPool) null);
      // Undeclared exception!
      try { 
        synthetic0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bcel.classfile.Utility", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      Constant[] constantArray0 = new Constant[4];
      ConstantPool constantPool0 = new ConstantPool(constantArray0);
      Synthetic synthetic0 = new Synthetic((-1176), (-1176), byteArray0, constantPool0);
      DataOutputStream dataOutputStream0 = new DataOutputStream((OutputStream) null);
      // Undeclared exception!
      try { 
        synthetic0.dump(dataOutputStream0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.DataOutputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Synthetic synthetic0 = null;
      try {
        synthetic0 = new Synthetic((Synthetic) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bcel.classfile.Synthetic", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      byte[] byteArray0 = new byte[7];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0, 0, 0);
      DataInputStream dataInputStream0 = new DataInputStream(byteArrayInputStream0);
      Constant[] constantArray0 = new Constant[0];
      ConstantPool constantPool0 = new ConstantPool(constantArray0);
      Synthetic synthetic0 = null;
      try {
        synthetic0 = new Synthetic(1, 1, dataInputStream0, constantPool0);
        fail("Expecting exception: EOFException");
      
      } catch(Throwable e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.DataInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Synthetic synthetic0 = new Synthetic(1912, 1912, (byte[]) null, (ConstantPool) null);
      Attribute attribute0 = synthetic0.copy((ConstantPool) null);
      assertNotSame(attribute0, synthetic0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      DataInputStream dataInputStream0 = new DataInputStream((InputStream) null);
      Synthetic synthetic0 = new Synthetic(0, 0, dataInputStream0, (ConstantPool) null);
      String string0 = synthetic0.toString();
      assertEquals("Synthetic", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      byte[] byteArray0 = new byte[8];
      Constant[] constantArray0 = new Constant[0];
      ConstantPool constantPool0 = new ConstantPool(constantArray0);
      ByteArrayOutputStream byteArrayOutputStream0 = new ByteArrayOutputStream((byte)30);
      DataOutputStream dataOutputStream0 = new DataOutputStream(byteArrayOutputStream0);
      Synthetic synthetic0 = new Synthetic(45, 147, byteArray0, constantPool0);
      // Undeclared exception!
      try { 
        synthetic0.dump(dataOutputStream0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.ByteArrayOutputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      DataInputStream dataInputStream0 = new DataInputStream((InputStream) null);
      Synthetic synthetic0 = new Synthetic(0, 0, dataInputStream0, (ConstantPool) null);
      MockFile mockFile0 = new MockFile("&AGsN");
      MockPrintStream mockPrintStream0 = new MockPrintStream(mockFile0);
      DataOutputStream dataOutputStream0 = new DataOutputStream(mockPrintStream0);
      synthetic0.dump(dataOutputStream0);
      assertEquals(0, synthetic0.getNameIndex());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      FileDescriptor fileDescriptor0 = new FileDescriptor();
      MockFileInputStream mockFileInputStream0 = new MockFileInputStream(fileDescriptor0);
      DataInputStream dataInputStream0 = new DataInputStream(mockFileInputStream0);
      Synthetic synthetic0 = null;
      try {
        synthetic0 = new Synthetic(7, 7, dataInputStream0, (ConstantPool) null);
        fail("Expecting exception: IOException");
      
      } catch(Throwable e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.NativeMockedIO", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      Constant[] constantArray0 = new Constant[4];
      ConstantPool constantPool0 = new ConstantPool(constantArray0);
      Synthetic synthetic0 = new Synthetic((-1176), (-1176), byteArray0, constantPool0);
      Synthetic synthetic1 = new Synthetic(synthetic0);
      assertEquals((-1176), synthetic1.getNameIndex());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      DataInputStream dataInputStream0 = new DataInputStream((InputStream) null);
      Synthetic synthetic0 = new Synthetic(0, 0, dataInputStream0, (ConstantPool) null);
      byte[] byteArray0 = new byte[4];
      synthetic0.setBytes(byteArray0);
      Attribute attribute0 = synthetic0.copy((ConstantPool) null);
      assertNotSame(attribute0, synthetic0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Synthetic synthetic0 = new Synthetic(1912, 1912, (byte[]) null, (ConstantPool) null);
      byte[] byteArray0 = synthetic0.getBytes();
      assertNull(byteArray0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      byte[] byteArray0 = new byte[7];
      Synthetic synthetic0 = new Synthetic(0, 0, byteArray0, (ConstantPool) null);
      EmptyVisitor emptyVisitor0 = new EmptyVisitor();
      synthetic0.accept(emptyVisitor0);
      assertEquals((byte)7, synthetic0.getTag());
  }
}
