/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 16 19:29:53 GMT 2021
 */

package org.apache.bcel.verifier.statics;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.bcel.verifier.VerificationResult;
import org.apache.bcel.verifier.Verifier;
import org.apache.bcel.verifier.statics.Pass3aVerifier;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Pass3aVerifier_ESTest extends Pass3aVerifier_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Verifier verifier0 = mock(Verifier.class, new ViolatedAssumptionAnswer());
      Pass3aVerifier pass3aVerifier0 = new Pass3aVerifier(verifier0, 0);
      int int0 = pass3aVerifier0.getMethodNo();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Verifier verifier0 = mock(Verifier.class, new ViolatedAssumptionAnswer());
      Pass3aVerifier pass3aVerifier0 = new Pass3aVerifier(verifier0, (-184));
      int int0 = pass3aVerifier0.getMethodNo();
      assertEquals((-184), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Pass3aVerifier pass3aVerifier0 = new Pass3aVerifier((Verifier) null, 2708);
      // Undeclared exception!
      try { 
        pass3aVerifier0.do_verify();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bcel.verifier.statics.Pass3aVerifier", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      VerificationResult verificationResult0 = mock(VerificationResult.class, new ViolatedAssumptionAnswer());
      Verifier verifier0 = mock(Verifier.class, new ViolatedAssumptionAnswer());
      doReturn(verificationResult0).when(verifier0).doPass2();
      Pass3aVerifier pass3aVerifier0 = new Pass3aVerifier(verifier0, 2);
      pass3aVerifier0.do_verify();
      assertEquals(2, pass3aVerifier0.getMethodNo());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Verifier verifier0 = mock(Verifier.class, new ViolatedAssumptionAnswer());
      Pass3aVerifier pass3aVerifier0 = new Pass3aVerifier(verifier0, 2);
      int int0 = pass3aVerifier0.getMethodNo();
      assertEquals(2, int0);
  }
}
