/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 16 15:18:43 GMT 2021
 */

package org.apache.bcel.generic;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.bcel.generic.GOTO;
import org.apache.bcel.generic.InstructionHandle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GotoInstruction_ESTest extends GotoInstruction_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GOTO gOTO0 = new GOTO();
      assertEquals(0, gOTO0.getIndex());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GOTO gOTO0 = new GOTO((InstructionHandle) null);
      assertEquals((short)167, gOTO0.getOpcode());
  }
}
