/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 16 19:18:49 GMT 2021
 */

package org.apache.bcel.verifier;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.bcel.verifier.Verifier;
import org.apache.bcel.verifier.VerifierFactory;
import org.apache.bcel.verifier.VerifierFactoryListModel;
import org.apache.bcel.verifier.VerifierFactoryObserver;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class VerifierFactory_ESTest extends VerifierFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Verifier verifier0 = VerifierFactory.getVerifier("org.apache.bcel.verifier.VerifierFactory");
      assertEquals("org.apache.bcel.verifier.VerifierFactory", verifier0.getClassName());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      VerifierFactoryListModel verifierFactoryListModel0 = new VerifierFactoryListModel();
      //  // Unstable assertion: assertEquals(1, verifierFactoryListModel0.getSize());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      VerifierFactory.getVerifiers();
      Verifier verifier0 = VerifierFactory.getVerifier("Qd/.J/J!bz7G?x{1");
      assertEquals("Qd/.J/J!bz7G?x{1", verifier0.getClassName());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      VerifierFactory.detach((VerifierFactoryObserver) null);
  }
}
