/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 16 18:54:08 GMT 2021
 */

package org.apache.bcel.verifier.structurals;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.bcel.classfile.Constant;
import org.apache.bcel.classfile.ConstantPool;
import org.apache.bcel.generic.ConstantPoolGen;
import org.apache.bcel.generic.InstructionList;
import org.apache.bcel.generic.MethodGen;
import org.apache.bcel.generic.ObjectType;
import org.apache.bcel.generic.Type;
import org.apache.bcel.verifier.VerificationResult;
import org.apache.bcel.verifier.Verifier;
import org.apache.bcel.verifier.structurals.Pass3bVerifier;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Pass3bVerifier_ESTest extends Pass3bVerifier_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Pass3bVerifier pass3bVerifier0 = new Pass3bVerifier((Verifier) null, 155);
      int int0 = pass3bVerifier0.getMethodNo();
      assertEquals(155, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Verifier verifier0 = mock(Verifier.class, new ViolatedAssumptionAnswer());
      Pass3bVerifier pass3bVerifier0 = new Pass3bVerifier(verifier0, (-2849));
      int int0 = pass3bVerifier0.getMethodNo();
      assertEquals((-2849), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Pass3bVerifier pass3bVerifier0 = new Pass3bVerifier((Verifier) null, 155);
      ObjectType objectType0 = Type.CLASS;
      InstructionList instructionList0 = new InstructionList();
      Constant[] constantArray0 = new Constant[0];
      ConstantPool constantPool0 = new ConstantPool(constantArray0);
      ConstantPoolGen constantPoolGen0 = new ConstantPoolGen(constantPool0);
      MethodGen methodGen0 = new MethodGen(155, objectType0, objectType0.NO_ARGS, (String[]) null, "if_acmpeq", "if_acmpeq", instructionList0, constantPoolGen0);
      // Undeclared exception!
      try { 
        pass3bVerifier0.invalidReturnTypeError(objectType0, methodGen0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Returned type java.lang.Class does not match Method's return type java.lang.Class
         //
         verifyException("org.apache.bcel.verifier.structurals.Pass3bVerifier", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Pass3bVerifier pass3bVerifier0 = new Pass3bVerifier((Verifier) null, 1383);
      // Undeclared exception!
      try { 
        pass3bVerifier0.do_verify();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bcel.verifier.structurals.Pass3bVerifier", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      VerificationResult verificationResult0 = mock(VerificationResult.class, new ViolatedAssumptionAnswer());
      Verifier verifier0 = mock(Verifier.class, new ViolatedAssumptionAnswer());
      doReturn(verificationResult0).when(verifier0).doPass3a(anyInt());
      Pass3bVerifier pass3bVerifier0 = new Pass3bVerifier(verifier0, 1448);
      pass3bVerifier0.do_verify();
      assertEquals(1448, pass3bVerifier0.getMethodNo());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Verifier verifier0 = mock(Verifier.class, new ViolatedAssumptionAnswer());
      Pass3bVerifier pass3bVerifier0 = new Pass3bVerifier(verifier0, 0);
      int int0 = pass3bVerifier0.getMethodNo();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Verifier verifier0 = mock(Verifier.class, new ViolatedAssumptionAnswer());
      Pass3bVerifier pass3bVerifier0 = new Pass3bVerifier(verifier0, 1448);
      ObjectType objectType0 = Type.THROWABLE;
      // Undeclared exception!
      try { 
        pass3bVerifier0.invalidReturnTypeError(objectType0, (MethodGen) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bcel.verifier.structurals.Pass3bVerifier", e);
      }
  }
}
